name: flutter_project_name_changer
description: "A Dart package for programmatically renaming occurrences of a project name in Dart files."
version: 1.0.4
maintainer: Sai
homepage: https://github.com/usaikoo/flutter_project_name_changer

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
